export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS"
}

export const registerConstants = {
    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE"
}

export const categoryConstasnts ={
    GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE:"GET_ALL_CATEGORIES_FAILURE",

    ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE"
}
