export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_SCCESS : "LOGOUT_SCCESS"
}

export const registerConstants = {
    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE"
}